apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::339712894994:role/eksctl-cloudmart-nodegroup-standar-NodeInstanceRole-78zm6ApEmQMQ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::339712894994:role/codebuild-cloudmartDeployToProduction1-service-role
      username: build
